-- QUES 1 ) FIND CITY , REGION_ID OF THE CITY WHOSE NAMES STARTS WITH "R"

SELECT L.CITY ,R. REGION_ID  FROM COUNTRIES AS C
INNER JOIN LOCATIONS AS L
ON C.COUNTRY_ID = L.COUNTRY_ID
INNER JOIN REGIONS AS R
ON R.REGION_ID = C.REGION_ID
WHERE L.CITY LIKE "R%" ;

-- QUES 2 ) TO FIND THE NAME IN ALPHABATICAL ORDER , MIN(SALARY) AND MAX(SALARY) OF TOP 5 EMPLOYEES 

SELECT CONCAT(FIRST_NAME," ",LAST_NAME) AS NAME , MIN_SALARY , MAX_SALARY FROM EMPLOYEES AS E
INNER JOIN JOBS AS J
ON E.JOB_ID = J.JOB_ID
ORDER BY NAME
LIMIT 5 ;

-- QUES 3 ) TO FIND THE NAME OF THE EMPLOYEES WHO HAVE JOB HISTORY START_DATE IN JANUARY AND END_DATE IN JULY 

SELECT CONCAT(FIRST_NAME, " " , LAST_NAME) AS NAME , START_DATE , END_DATE FROM employees AS E
INNER JOIN JOB_HISTORY AS JH
ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
WHERE MONTH(START_DATE) = 1 AND MONTH(END_DATE) = 7 ;


-- QUES 4) TO FIND THE NAME OF THE COUNTRY, DEPARTMENT_NAME , STATE PROVINCE , REGION_NAME AND
-- CITY STARTING WITH "S" AND DEPARTMENT NAME ENDING WITH "Y"

SELECT COUNTRY_NAME , CITY , DEPARTMENT_NAME , STATE_PROVINCE , REGION_NAME FROM COUNTRIES AS C 
INNER JOIN REGIONS AS R
ON C.REGION_ID = R.REGION_ID
INNER JOIN LOCATIONS AS L
ON L.COUNTRY_ID = C.COUNTRY_ID
INNER JOIN departments AS D
ON D.LOCATION_ID = L.LOCATION_ID
WHERE CITY LIKE "S%" AND DEPARTMENT_NAME LIKE "%Y";



